// +build !ignore_autogenerated

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"github.com/customer-api/customer-api-operator/pkg/apis/customer/v1alpha1.Customer":       schema_pkg_apis_customer_v1alpha1_Customer(ref),
		"github.com/customer-api/customer-api-operator/pkg/apis/customer/v1alpha1.CustomerSpec":   schema_pkg_apis_customer_v1alpha1_CustomerSpec(ref),
		"github.com/customer-api/customer-api-operator/pkg/apis/customer/v1alpha1.CustomerStatus": schema_pkg_apis_customer_v1alpha1_CustomerStatus(ref),
	}
}

func schema_pkg_apis_customer_v1alpha1_Customer(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "Customer is the Schema for the customers API",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/customer-api/customer-api-operator/pkg/apis/customer/v1alpha1.CustomerSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/customer-api/customer-api-operator/pkg/apis/customer/v1alpha1.CustomerStatus"),
						},
					},
					"firstName": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
					"lastName": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
					"email": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/customer-api/customer-api-operator/pkg/apis/customer/v1alpha1.CustomerSpec", "github.com/customer-api/customer-api-operator/pkg/apis/customer/v1alpha1.CustomerStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_customer_v1alpha1_CustomerSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "CustomerSpec defines the desired state of Customer",
				Type:        []string{"object"},
			},
		},
	}
}

func schema_pkg_apis_customer_v1alpha1_CustomerStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "CustomerStatus defines the observed state of Customer",
				Type:        []string{"object"},
			},
		},
	}
}
